spring:
  datasource:
    url: 
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  thymeleaf:
    cache: false
  mvc:
    format:
      date: yyyy-MM-dd